---
services:

  mainnetwork:
    image: alpine:3.20.0
    container_name: mainnetwork
    command: ["tail", "-f", "/dev/null"]
    ports:
      - ${APP_PORT:-80}:80
      - ${APP_SSL_PORT:-443}:443

  traefik:
    image: traefik:v3.3
    container_name: traefik
    env_file: "./.env"
    restart: unless-stopped
    network_mode: service:mainnetwork
    environment:
      - TRAEFIK_PROVIDERS_FILE_FILENAME=/traefik-config/dynamic.yml
      - TRAEFIK_PROVIDERS_FILE_WATCH=true
      - TRAEFIK_ENTRYPOINTS_WEB_ADDRESS=:80
      - TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS=:443
      - TRAEFIK_CERTIFICATESRESOLVERS_MYRESOLVER_ACME_STORAGE=/letsencrypt/acme.json
      - TRAEFIK_CERTIFICATESRESOLVERS_MYRESOLVER_ACME_TLSCHALLENGE=true
      - TRAEFIK_LOG_LEVEL=DEBUG
      - TRAEFIK_LOG=true
      - TRAEFIK_LOG_FORMAT=common
      - TRAEFIK_ACCESSLOG=false
      - TRAEFIK_ACCESSLOG_FILEPATH=/var/log/traefik/access.log
      - TRAEFIK_ACCESSLOG_FORMAT=common
    entrypoint: ["sh", "-c", "/generate_dynamic_config.sh && traefik"]
    volumes:
      - "traefik-certificates:/letsencrypt"
      - "./generate_dynamic_config.sh:/generate_dynamic_config.sh:ro"
      - "/traefik-config"
    depends_on:
      - mainnetwork

  backend:
    build: ../backend
    container_name: backend
    env_file: "./.env"
    restart: unless-stopped
    network_mode: service:mainnetwork
    environment:
      - DATABASE_PATH=/app/data/star_schema.db
    volumes:
      - ./data:/app/data
    depends_on:
      - mainnetwork

  frontend:
    build:
      context: ../frontend
      args:
        - NEXT_PUBLIC_GRAPHQL_ENDPOINT=${NEXT_PUBLIC_GRAPHQL_ENDPOINT}
    container_name: frontend
    env_file: "./.env"
    restart: unless-stopped
    network_mode: service:mainnetwork
    depends_on:
      - backend

volumes:
  traefik-certificates:
